package com.blog.ssh.test.cxf.client.generateFile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-08-26T10:27:05.693+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ToolInterfaceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ToolInterfaceSoap {

    @WebResult(name = "InteractionOperatingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InteractionOperating", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InteractionOperating")
    @WebMethod(operationName = "InteractionOperating", action = "http://tempuri.org/InteractionOperating")
    @ResponseWrapper(localName = "InteractionOperatingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InteractionOperatingResponse")
    public java.lang.String interactionOperating(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        java.lang.String request
    );

    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @WebMethod(operationName = "Login", action = "http://tempuri.org/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        java.lang.String request
    );
}
