package com.blog.ssh.test.cxf.client.generateFile;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-08-26T10:27:05.779+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ToolInterface", 
                  wsdlLocation = "http://171.221.218.21:5418/ToolInterface.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ToolInterface extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ToolInterface");
    public final static QName ToolInterfaceSoap12 = new QName("http://tempuri.org/", "ToolInterfaceSoap12");
    public final static QName ToolInterfaceSoap = new QName("http://tempuri.org/", "ToolInterfaceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://171.221.218.21:5418/ToolInterface.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ToolInterface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://171.221.218.21:5418/ToolInterface.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ToolInterface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ToolInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ToolInterface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ToolInterface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ToolInterface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ToolInterface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ToolInterfaceSoap
     */
    @WebEndpoint(name = "ToolInterfaceSoap12")
    public ToolInterfaceSoap getToolInterfaceSoap12() {
        return super.getPort(ToolInterfaceSoap12, ToolInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToolInterfaceSoap
     */
    @WebEndpoint(name = "ToolInterfaceSoap12")
    public ToolInterfaceSoap getToolInterfaceSoap12(WebServiceFeature... features) {
        return super.getPort(ToolInterfaceSoap12, ToolInterfaceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ToolInterfaceSoap
     */
    @WebEndpoint(name = "ToolInterfaceSoap")
    public ToolInterfaceSoap getToolInterfaceSoap() {
        return super.getPort(ToolInterfaceSoap, ToolInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToolInterfaceSoap
     */
    @WebEndpoint(name = "ToolInterfaceSoap")
    public ToolInterfaceSoap getToolInterfaceSoap(WebServiceFeature... features) {
        return super.getPort(ToolInterfaceSoap, ToolInterfaceSoap.class, features);
    }

}
